sudo: required
dist: trusty
language: c++

before_install:
  - sudo apt-get install ros-indigo-roscpp ros-indigo-pcl-ros ros-indigo-navigation

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
 - ./gradlew build -PmakeSim
